version: '3.8'
services:
  ### Node #########################################
  node:
    build:
      context: ./docker/node
    container_name: "remix_node"
    volumes:
      - ./:/app
      - ./docker/.dock-data/yarn-cache:/usr/local/share/.cache/yarn/v6
    ports:
      - "3000:3000"
      - "3800:3800"
    tty: true

